name: Test YAMLLint and YAMLFixer

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install --user yamllint yamlfixer-opt-nc

      - name: YAMLLint and YAMLFixer
        env:
          YAMLLINT_RULES: "{extends: default, rules: {line-length: disable, document-start: {present: false}}}"
        run: |
          yaml_files=$(find . -maxdepth 1 -type f -iname "*.yaml" -or -iname "*.yml")
          for file in $yaml_files; do
            yamlfixer -C "$YAMLLINT_RULES" "$file"
          done
